apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-obyv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dhsg-tenant/rhtap-demo-app/hacbs-test-project-obyv@sha256:b945637bfb9b69fb40fd0a48a92b500b47a9e0aa79930538fdc192cc7a6c37c9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
